### PR TITLE
Update support to Intercom API v2

### PR DESCRIPTION
**Pull request by mgoodfellow**
The Intercom API has been changed for [v2 support](https://doc.intercom.io/api/)

I have removed the endpoints and handlers which are no longer supported in v2, and added a couple more features which are, such as [Events](https://doc.intercom.io/api/#events)

Before starting the work, I cleaned up the repo by removing bin/obj folders and adding a .gitignore file.

This also now will adhere to rate limiting responses and throw exceptions accordingly

### CODE REVIEW

**Comment by mgoodfellow** [comment]
Just as an aside, I have been using this in production for a while. It would be great if people can add the new endpoints as and when they need them! :)

**Comment by AlbertoLeon** [comment]
I will use this PR so I expect @tarr11 will accept it. Thanks for the stuff!

**Comment by tarr11** [comment]
@mgoodfellow I don't have much time to work on this (not doing a whole lot of .NET right now), seems like you've done quite a bit in here.  Would you like to be added as a collaborator?

**Comment by mgoodfellow** [comment]
@tarr11 Yes, that would be brilliant, thanks - I'm happy to spend a bit of time on it

I will refresh the nuget bits tomorrow to get it upissued etc.

**Comment by tarr11** [comment]
Ok done.  Send me your nuget username if you want write access to that repo.

**Comment by mgoodfellow** [comment]
Just set one up - it's also mgoodfellow. Thanks!

**Comment by tarr11** [comment]
Ok you've been added as a nuget owner

**Pull request merged**
