### PR TITLE
Added Companies post.

### PR DESCRIPTION
**Pull request by durop**
Added companies post --> https://doc.intercom.io/api/#company-model

Example:
string apikey = "";
string appid = "";
var client = IntercomClient.GetClient(appid, apikey);
client.Companies.Post(new { company_id = "119", name = "Company new name" });

### CODE REVIEW

**Comment by mgoodfellow** [comment]
Hi @durop,

Thanks for the PR! Is it possible to also add the GET functions? From what I can see there is the option to [list all companies](https://doc.intercom.io/api/#list-companies), or [list via tag/segment](https://doc.intercom.io/api/#list-by-tag-or-segment), and the 3rd would simply be [view company](https://doc.intercom.io/api/#view-a-company)?

Other than that, it looks great - but with these endpoints it would provide the completed set.

Let me know either way!

Thanks!

**Comment by durop** [comment]
Hi @mgoodfellow!
I added the methods you mentioned.
I didn't test the method GetCompanyList by tag_id but should work.

:+1:

**Comment by mgoodfellow** [comment]
Thanks @durop, LGTM :+1: 

I will package a new version of the NuGet library

**Comment by durop** [comment]
Excelent! Already using the new version : D

**Pull request merged**
